CREATE TABLE [Catalogo].[Macronutrientes]
(
	[idMacronutrientes] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[Codigo] NVARCHAR(50) NOT NULL,
	[Nombre] NVARCHAR(50) NULL,
	[Descripcion] NVARCHAR(150) NULL,
	[Hco] DECIMAL(2, 2) NOT NULL,
	[Lipidos] DECIMAL(2, 2) NOT NULL,
	[Proteina] DECIMAL(2, 2) NOT NULL,
	[Activo] BIT NOT NULL DEFAULT(1),
	[UpdDateTime] DATETIMEOFFSET(7) NOT NULL DEFAULT(SYSDATETIMEOFFSET()),
	[InsDateTime] DATETIMEOFFSET(7) NOT NULL DEFAULT(SYSDATETIMEOFFSET())
)
