CREATE TABLE [Seguridad].[Usuario]
(
	[idUsuario] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[Usuario] NVARCHAR(50) NOT NULL,
	[Contraseña] NVARCHAR(50) NOT NULL,
	[Activo] BIT NOT NULL DEFAULT(1),
	[UpdDateTime] DATETIMEOFFSET(7) NOT NULL DEFAULT(SYSDATETIMEOFFSET()),
	[InsDateTime] DATETIMEOFFSET(7) NOT NULL DEFAULT(SYSDATETIMEOFFSET())
)
