CREATE TABLE [Paciente].[Paciente]
(
	[idPaciente] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[Nombre] NVARCHAR(50) NOT NULL,
	[SegundoNombre] NVARCHAR(50) NULL,
	[Apellido_P] NVARCHAR(50) NOT NULL,
	[Apellido_M] NVARCHAR(50) NULL,
	[Email] NVARCHAR(100) NULL,
	[Celular] NVARCHAR(10) NULL,
	[Activo] BIT NOT NULL DEFAULT(1),
	[UpdDateTime] DATETIMEOFFSET(7) NOT NULL DEFAULT(SYSDATETIMEOFFSET()),
	[InsDateTime] DATETIMEOFFSET(7) NOT NULL DEFAULT(SYSDATETIMEOFFSET())
)