CREATE TABLE [Alimento].[Alimento]
(
	[idAlimento] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[idTipoAlimento] INT NOT NULL,
	[Nombre] NVARCHAR(100) NOT NULL,
	[Cantidad] NUMERIC(18, 0) NOT NULL,
	[idUnidad] INT NOT NULL,
	[PesoBruto] NUMERIC(18, 0) NOT NULL,
	[PesoNeto] NUMERIC(18, 0) NOT NULL,
	[Energia] NUMERIC(18, 0) NOT NULL,
	[Proteina] NUMERIC(18, 0) NOT NULL,
	[Lipidos] NUMERIC(18, 0) NOT NULL,
	[Hco] NUMERIC(18, 0) NOT NULL,
	[Fibra] NUMERIC(18, 0) NULL,
	[VitaminaA] NUMERIC(18, 0) NULL,
	[AcidoAscorbico] NUMERIC(18, 0) NULL,
	[AcidoFolico] NUMERIC(18, 0) NULL,
	[Hierro] NUMERIC(18, 0) NULL,
	[Potasio] NUMERIC(18, 0) NULL,
	[IndGlicemico] NUMERIC(18, 0) NULL,
	[CargaGlicemica] NUMERIC(18, 0) NULL,
	[Azucar] NUMERIC(18, 0) NULL,
	[Sodio] NUMERIC(18, 0) NULL,
	[Calcio] NUMERIC(18, 0) NULL,
	[Selenio] NUMERIC(18, 0) NULL,
	[Fosforo] NUMERIC(18, 0) NULL,
	[Colesterol] NUMERIC(18, 0) NULL,
	[Activo] BIT NULL DEFAULT(1),
	[UpdDateTime] DATETIMEOFFSET(7) NOT NULL DEFAULT(SYSDATETIMEOFFSET()),
	[InsDateTime] DATETIMEOFFSET(7) NOT NULL DEFAULT(SYSDATETIMEOFFSET()),
	FOREIGN KEY (idTipoAlimento) REFERENCES [Alimento].[TipoAlimento](idTipoAlimento),
	FOREIGN KEY (idUnidad) REFERENCES [Alimento].[Unidad](idUnidad)
)
